// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpcaEfucRRcm_zjzEqcSPCo-GWaFk4sSo',
    appId: '1:426890911480:web:33b48e41991fc2439b250d',
    messagingSenderId: '426890911480',
    projectId: 'expense-tracker-50365',
    authDomain: 'expense-tracker-50365.firebaseapp.com',
    storageBucket: 'expense-tracker-50365.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPtgFthf15CdrEiYhqKfh7mQoQpkhXkXU',
    appId: '1:426890911480:android:78400de8de49c40c9b250d',
    messagingSenderId: '426890911480',
    projectId: 'expense-tracker-50365',
    storageBucket: 'expense-tracker-50365.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiGIzgqw8YkybHYpIsFtYgKsgui1Y7sdk',
    appId: '1:426890911480:ios:26d708894f01c9ea9b250d',
    messagingSenderId: '426890911480',
    projectId: 'expense-tracker-50365',
    storageBucket: 'expense-tracker-50365.firebasestorage.app',
    iosBundleId: 'com.example.tracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBiGIzgqw8YkybHYpIsFtYgKsgui1Y7sdk',
    appId: '1:426890911480:ios:26d708894f01c9ea9b250d',
    messagingSenderId: '426890911480',
    projectId: 'expense-tracker-50365',
    storageBucket: 'expense-tracker-50365.firebasestorage.app',
    iosBundleId: 'com.example.tracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCpcaEfucRRcm_zjzEqcSPCo-GWaFk4sSo',
    appId: '1:426890911480:web:44f4b8528b56aa529b250d',
    messagingSenderId: '426890911480',
    projectId: 'expense-tracker-50365',
    authDomain: 'expense-tracker-50365.firebaseapp.com',
    storageBucket: 'expense-tracker-50365.firebasestorage.app',
  );
}
